         replicaCount: '2')

stage 'verify deploy in test'
openshiftVerifyDeployment(namespace: 'testing',
               depCfg: 'myapp',
               replicaCount:'2',
               verifyReplicaCount: 'true',
               waitTime: '300000')

stage 'deploy to production'
timeout(time: 2, unit: 'DAYS') {
    input message: 'Approve to production?'
}

openshiftTag(namespace: 'development',
      sourceStream: 'myapp',
      sourceTag: 'latest',
      destinationStream: 'myapp',
      destinationTag: 'promotePRD')

openshiftDeploy(namespace: 'production',
         deploymentConfig: 'myapp',
         waitTime: '300000')

openshiftScale(namespace: 'production',
         deploymentConfig: 'myapp',
         waitTime: '300000',
         replicaCount: '2')

stage 'verify deploy in production'
openshiftVerifyDeployment(namespace: 'production',
               depCfg: 'myapp',
               replicaCount:'2',
               verifyReplicaCount: 'true',
               waitTime: '300000')
}
